# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tango/PycharmProjects/Med/followupwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Mediator

class Ui_HistoryWindow(object):
    def setupUi(self, HistoryWindow,pat):
        HistoryWindow.setObjectName("HistoryWindow")
        HistoryWindow.resize(1280, 960)
        self.mainwindow = HistoryWindow
        self.centralwidget = QtWidgets.QWidget(HistoryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.label.setObjectName("label")
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(50, 10, 110, 26))
        self.date.setReadOnly(True)
        self.date.setDate(QtCore.QDate(2019, 1, 1))
        self.date.setObjectName("date")
        self.date.setDate(QtCore.QDate.fromString(pat.caserecord.date,"dd/MM/yy"))
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 71, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 71, 17))
        self.label_3.setObjectName("label_3")
        self.subjective = QtWidgets.QTextEdit(self.centralwidget)
        self.subjective.setGeometry(QtCore.QRect(10, 90, 501, 201))
        self.subjective.setReadOnly(False)
        self.subjective.setObjectName("subjective")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(640, 70, 131, 17))
        self.label_4.setObjectName("label_4")
        self.objective = QtWidgets.QTextEdit(self.centralwidget)
        self.objective.setGeometry(QtCore.QRect(640, 90, 581, 201))
        self.objective.setReadOnly(False)
        self.objective.setObjectName("objective")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 300, 121, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 320, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 350, 67, 17))
        self.label_7.setObjectName("label_7")
        self.appetite = QtWidgets.QLineEdit(self.centralwidget)
        self.appetite.setGeometry(QtCore.QRect(140, 320, 113, 25))
        self.appetite.setObjectName("appetite")
        self.thirst = QtWidgets.QLineEdit(self.centralwidget)
        self.thirst.setGeometry(QtCore.QRect(140, 350, 113, 25))
        self.thirst.setObjectName("thirst")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 380, 67, 17))
        self.label_8.setObjectName("label_8")
        self.sleep = QtWidgets.QLineEdit(self.centralwidget)
        self.sleep.setGeometry(QtCore.QRect(140, 380, 113, 25))
        self.sleep.setObjectName("sleep")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 410, 67, 17))
        self.label_9.setObjectName("label_9")
        self.bowel = QtWidgets.QLineEdit(self.centralwidget)
        self.bowel.setGeometry(QtCore.QRect(140, 410, 113, 25))
        self.bowel.setObjectName("bowel")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 440, 67, 17))
        self.label_10.setObjectName("label_10")
        self.urine = QtWidgets.QLineEdit(self.centralwidget)
        self.urine.setGeometry(QtCore.QRect(140, 440, 113, 25))
        self.urine.setObjectName("urine")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 470, 67, 17))
        self.label_11.setObjectName("label_11")
        self.sweat = QtWidgets.QLineEdit(self.centralwidget)
        self.sweat.setGeometry(QtCore.QRect(140, 470, 113, 25))
        self.sweat.setObjectName("sweat")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(310, 300, 121, 17))
        self.label_12.setObjectName("label_12")
        self.lab = QtWidgets.QTextEdit(self.centralwidget)
        self.lab.setGeometry(QtCore.QRect(310, 320, 441, 171))
        self.lab.setObjectName("lab")
        self.pam = QtWidgets.QLabel(self.centralwidget)
        self.pam.setGeometry(QtCore.QRect(780, 300, 121, 17))
        self.pam.setObjectName("pam")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(780, 320, 441, 171))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(60, 510, 67, 17))
        self.label_13.setObjectName("label_13")
        self.events = QtWidgets.QTextEdit(self.centralwidget)
        self.events.setGeometry(QtCore.QRect(60, 530, 401, 211))
        self.events.setObjectName("events")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(480, 510, 151, 17))
        self.label_14.setObjectName("label_14")
        self.totality = QtWidgets.QTextEdit(self.centralwidget)
        self.totality.setGeometry(QtCore.QRect(480, 530, 411, 211))
        self.totality.setObjectName("totality")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(60, 750, 211, 17))
        self.label_15.setObjectName("label_15")
        self.comments = QtWidgets.QTextEdit(self.centralwidget)
        self.comments.setGeometry(QtCore.QRect(60, 770, 491, 141))
        self.comments.setObjectName("comments")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(580, 750, 67, 17))
        self.label_16.setObjectName("label_16")
        self.rx = QtWidgets.QTextEdit(self.centralwidget)
        self.rx.setGeometry(QtCore.QRect(580, 770, 501, 141))
        self.rx.setObjectName("rx")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1050, 10, 67, 17))
        self.label_17.setObjectName("label_17")
        self.op_no = QtWidgets.QLineEdit(self.centralwidget)
        self.op_no.setGeometry(QtCore.QRect(1110, 10, 113, 25))
        self.op_no.setObjectName("op_no")
        self.op_no.setText(pat.op_no)
        self.op_no.setReadOnly(True)


        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setGeometry(QtCore.QRect(1100, 890, 89, 25))
        self.prevButton.setObjectName("prevButton")
        self.doneButton = QtWidgets.QPushButton(self.centralwidget)
        self.doneButton.setGeometry(QtCore.QRect(1190, 890, 89, 25))
        self.doneButton.setObjectName("doneButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(910, 530, 351, 211))
        self.textEdit.setObjectName("textEdit")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(910, 510, 67, 17))
        self.label_18.setObjectName("label_18")
        HistoryWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HistoryWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        HistoryWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HistoryWindow)
        self.statusbar.setObjectName("statusbar")
        HistoryWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HistoryWindow)
        QtCore.QMetaObject.connectSlotsByName(HistoryWindow)

        self.prevButton.clicked.connect(self.prevWindow)

    def retranslateUi(self, HistoryWindow):
        _translate = QtCore.QCoreApplication.translate
        HistoryWindow.setWindowTitle(_translate("HistoryWindow", "MainWindow"))
        self.label.setText(_translate("HistoryWindow", "Date"))
        self.label_2.setText(_translate("HistoryWindow", "Symptoms"))
        self.label_3.setText(_translate("HistoryWindow", "Subjective"))
        self.label_4.setText(_translate("HistoryWindow", "Objective Findings"))
        self.label_5.setText(_translate("HistoryWindow", "Physical Generals"))
        self.label_6.setText(_translate("HistoryWindow", "Appetite"))
        self.label_7.setText(_translate("HistoryWindow", "Thirst"))
        self.label_8.setText(_translate("HistoryWindow", "Sleep"))
        self.label_9.setText(_translate("HistoryWindow", "Bowels"))
        self.label_10.setText(_translate("HistoryWindow", "Urine"))
        self.label_11.setText(_translate("HistoryWindow", "Sweat"))
        self.label_12.setText(_translate("HistoryWindow", "Lab Investigation"))
        self.pam.setText(_translate("HistoryWindow", "Physic & Mentals"))
        self.label_13.setText(_translate("HistoryWindow", "Events"))
        self.label_14.setText(_translate("HistoryWindow", "Totality of Symptoms"))
        self.label_15.setText(_translate("HistoryWindow", "Dr\'s Comments and Discussion"))
        self.label_16.setText(_translate("HistoryWindow", "Rx"))
        self.label_17.setText(_translate("HistoryWindow", "Op No."))
        self.prevButton.setText(_translate("HistoryWindow", "Previous"))
        self.doneButton.setText(_translate("HistoryWindow", "Done"))
        self.label_18.setText(_translate("HistoryWindow", "Rubrics"))

    def prevWindow(self):
        Mediator.newWindow(self,"CaseWindow",self.mainwindow,[self.op_no.text(),self.date.text()])

    def done(self):
        Mediator.readCaseRecord(self)
        Mediator.newWindow(self,"EntryWindow",self.mainwindow)





'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HistoryWindow = QtWidgets.QMainWindow()
    ui = Ui_HistoryWindow()
    ui.setupUi(HistoryWindow)
    HistoryWindow.show()
    sys.exit(app.exec_())'''
